# Used with Goland built-in REST API client
# https://www.jetbrains.com/help/go/http-client-in-product-code-editor.html

GET {{host}}

###

GET {{host}}/health

###

GET {{host}}/version

###

GET {{host}}/otusapp/ilazarev

###

GET {{host}}/otusapp/ilazarev/health
