# Used with Goland built-in REST API client
# https://www.jetbrains.com/help/go/http-client-in-product-code-editor.html

GET {{host}}
Host: arch.homework

###

GET {{host}}/health
Host: arch.homework

###

GET {{host}}/version
Host: arch.homework

###

GET {{host}}/otusapp/ilazarev
Host: arch.homework

###

GET {{host}}/otusapp/ilazarev/health
Host: arch.homework
