name: Build docker release

on:
  release:
    types: [created]

jobs:
  release-docker:
    name: release docker
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set APP_VERSION env
        run: echo "APP_VERSION=$(echo ${GITHUB_REF} | rev | cut -d'/' -f 1 | rev )" >> $GITHUB_ENV
      - name: Environment Printer
        uses: managedkaos/print-env@v1.0

      - uses: docker/build-push-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: strider2038/otus-micro-1
          always_pull: true
          build_args: APP_VERSION=${{ env.APP_VERSION }}
          tags: latest
          tag_with_ref: true
